In [ ]:
import numpy as np

arr1D = np.array([1, 2, 3, 4, 5])
print("1d array: ",arr1D, arr1D.shape, arr1D.ndim)

print()

arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print("2d array: ",arr2D, arr2D.shape, arr2D.ndim)

print()

arr3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3d array: ",arr3D, arr3D.shape, arr3D.ndim)

1d array:  [1 2 3 4 5] (5,) 1

2d array:  [[1 2 3]
 [4 5 6]] (2, 3) 2

3d array:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2) 3


In [ ]:


arr_range = np.arange(10, 51, 5)
print(arr_range)

[10 15 20 25 30 35 40 45 50]


In [ ]:


rand_matrix = np.random.randint(1, 21, size=(3, 3))
print(rand_matrix)

[[ 9 18 11]
 [ 7  3  5]
 [15  1 19]]


In [ ]:


arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print(arr[1])         # second row
print(arr[:, 0])      # first column
print(arr[0:2, 1:4])

[50 60 70 80]
[10 50 90]
[[20 30 40]
 [60 70 80]]


In [ ]:


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:


arr = np.arange(1, 13)
reshaped = arr.reshape(3, 4)

print(arr)
print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
